---
version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@3.0.0

parameters:
  action:
    type: enum
    enum:
      - build-check
    default: build-check
  project_root:
    type: string
    default: "helloworld-ms"


  ######################  executors  #############################################

executors:

  amd64_docker_executor:
    description: >
      An Ubuntu executor image.
    docker:
      - image: cimg/base:2025.06
    resource_class: large

  jdk21_executor:
    description: >
      A Java 21 VM executor.
    docker:
      - image: cimg/openjdk:21.0
    resource_class: large

  node_executor:
    description: >
      A NodeJS 24 executor.
    docker:
      - image: cimg/node:24.2
    resource_class: large


######################  jobs  ##################################################

jobs:

  ####################  build-check-job  #######################################
  ##
  build-check-job:
    description: >
      Job to run linter, build, and unit tests.
    executor: jdk21_executor
    steps:
      - checkout
      - run:
          name: Build and run unit tests
          command: |
            ./gradlew check -i

  ####################  sonar-scan-job  #######################################
  ##
  sonar-scan-job:
    description: >
      Job to run SonarQube scanner on project.
    executor: jdk21_executor
    steps:
      - checkout
      - run: ./gradlew check
      - sonarcloud/scan

######################  workflows  #############################################

workflows:

  ####################  main-workflow  ########################################
  ##
  main-workflow:
    when:
      equal: [build-check, << pipeline.parameters.action >>]
    jobs:
      - build-check-job:
          context:
            - repsy
      - sonar-scan-job:
          context:
            - repsy
            - sonarcloud

