apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: playground-cluster
  region: us-east-1

autoModeConfig:
  enabled: true

cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
    # enable specific types of cluster control plane logs
    # enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
